export const movies = [
  {
    id: 1,
    title: "The Dark Knight",
    plot: "Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and DA Harvey Dent, until a criminal mastermind known as the Joker thrusts Gotham into anarchy.",
    price: "$9.99",
    rating: 8.5,
    poster: "https://m.media-amazon.com/images/I/81IfoBox2TL.jpg",
    stars: 0,
    favourite: false,
    incart: false,
  },
  {
    id: 2,
    title: "Inception",
    plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    price: "$12.99",
    rating: 8.8,
    poster:
      "https://m.media-amazon.com/images/I/61gz2gcfkAL._AC_UF894,1000_QL80_.jpg",
    stars: 0,
    favourite: false,
    incart: false,
  },
  {
    id: 3,
    title: "Interstellar",
    plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    price: "$14.99",
    rating: 8.7,
    poster:
      "https://m.media-amazon.com/images/I/A1JVqNMI7UL._AC_UF894,1000_QL80_.jpg",
    stars: 0,
    favourite: false,
    incart: false,
  },
  {
    id: 4,
    title: "The Matrix",
    plot: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    price: "$11.99",
    rating: 8.7,
    poster:
      "https://m.media-amazon.com/images/I/51EG732BV3L._AC_UF894,1000_QL80_.jpg",
    stars: 0,
    favourite: false,
    incart: false,
  },
  {
    id: 5,
    title: "Pulp Fiction",
    plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    price: "$8.99",
    rating: 8.9,
    poster: "https://www.movieposters.com/cdn/shop/files/PulpFiction.Ver1.jpg",
    stars: 0,
    favourite: false,
    incart: false,
  },
  {
    id: 6,
    title: "Spider-Man: Into the Spider-Verse",
    plot: "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
    price: "$10.99",
    rating: 8.4,
    poster:
      "https://www.sonypictures.com/sites/default/files/styles/max_860x460/public/title-key-art/spidermanintothespiderverse_onesheet_1400x2100_2026.jpg",
    stars: 0,
    favourite: false,
    incart: false,
  },
  {
    id: 7,
    title: "Parasite",
    plot: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    price: "$13.99",
    rating: 8.5,
    poster:
      "https://assets.mubicdn.net/images/notebook/post_images/29843/images-w1400.jpg",
    stars: 0,
    favourite: false,
    incart: false,
  },
];
